export const flagData = {
    Afghanistan: "https://flagcdn.com/w320/af.png",
    Albania: "https://flagcdn.com/w320/al.png",
    Algeria: "https://flagcdn.com/w320/dz.png",
    Andorra: "https://flagcdn.com/w320/ad.png",
    Angola: "https://flagcdn.com/w320/ao.png",
    Anguilla: "https://flagcdn.com/w320/ai.png",
    "Antigua And Barbuda": "https://flagcdn.com/w320/ag.png",
    Argentina: "https://flagcdn.com/w320/ar.png",
    Armenia: "https://flagcdn.com/w320/am.png",
    Aruba: "https://flagcdn.com/w320/aw.png",
    Australia: "https://flagcdn.com/w320/au.png",
    Austria: "https://flagcdn.com/w320/at.png",
    Azerbaijan: "https://flagcdn.com/w320/az.png",
    Bahamas: "https://flagcdn.com/w320/bs.png",
    Bahrain: "https://flagcdn.com/w320/bh.png",
    Bangladesh: "https://flagcdn.com/w320/bd.png",
    Barbados: "https://flagcdn.com/w320/bb.png",
    Belarus: "https://flagcdn.com/w320/by.png",
    Belgium: "https://flagcdn.com/w320/be.png",
    Belize: "https://flagcdn.com/w320/bz.png",
    Benin: "https://flagcdn.com/w320/bj.png",
    Bermuda: "https://flagcdn.com/w320/bm.png",
    Bhutan: "https://flagcdn.com/w320/bt.png",
    Bolivia: "https://flagcdn.com/w320/bo.png",
    "Bosnia And Herzegovina": "https://flagcdn.com/w320/ba.png",
    Botswana: "https://flagcdn.com/w320/bw.png",
    Brazil: "https://flagcdn.com/w320/br.png",
    "British Virgin Islands": "https://flagcdn.com/w320/vg.png",
    "Brunei Darussalam": "https://flagcdn.com/w320/bn.png",
    Bulgaria: "https://flagcdn.com/w320/bg.png",
    "Burkina Faso": "https://flagcdn.com/w320/bf.png",
    Burundi: "https://flagcdn.com/w320/bi.png",
    "Cabo Verde": "https://flagcdn.com/w320/cv.png",
    Cambodia: "https://flagcdn.com/w320/kh.png",
    Cameroon: "https://flagcdn.com/w320/cm.png",
    Canada: "https://flagcdn.com/w320/ca.png",
    "Caribbean Netherlands": "https://flagcdn.com/w320/bq.png",
    "Cayman Islands": "https://flagcdn.com/w320/ky.png",
    "Central African Republic": "https://flagcdn.com/w320/cf.png",
    Chad: "https://flagcdn.com/w320/td.png",
    "Channel Islands": "https://flagcdn.com/w320/je.png",
    Chile: "https://flagcdn.com/w320/cl.png",
    "China Hong Kong Sar": "https://flagcdn.com/w320/hk.png",
    "China Macao Sar": "https://flagcdn.com/w320/mo.png",
    China: "https://flagcdn.com/w320/cn.png",
    Colombia: "https://flagcdn.com/w320/co.png",
    Comoros: "https://flagcdn.com/w320/km.png",
    Congo: "https://flagcdn.com/w320/cg.png",
    "Cook Islands": "https://flagcdn.com/w320/ck.png",
    "Costa Rica": "https://flagcdn.com/w320/cr.png",
    "Cote D Ivoire": "https://flagcdn.com/w320/ci.png",
    Croatia: "https://flagcdn.com/w320/hr.png",
    Cuba: "https://flagcdn.com/w320/cu.png",
    Curacao: "https://flagcdn.com/w320/cw.png",
    Cyprus: "https://flagcdn.com/w320/cy.png",
    "Czech Republic": "https://flagcdn.com/w320/cz.png",
    "Democratic Republic Of The Congo": "https://flagcdn.com/w320/cd.png",
    Denmark: "https://flagcdn.com/w320/dk.png",
    Djibouti: "https://flagcdn.com/w320/dj.png",
    Dominica: "https://flagcdn.com/w320/dm.png",
    "Dominican Republic": "https://flagcdn.com/w320/do.png",
    Ecuador: "https://flagcdn.com/w320/ec.png",
    Egypt: "https://flagcdn.com/w320/eg.png",
    "El Salvador": "https://flagcdn.com/w320/sv.png",
    "Equatorial Guinea": "https://flagcdn.com/w320/gq.png",
    Eritrea: "https://flagcdn.com/w320/er.png",
    Estonia: "https://flagcdn.com/w320/ee.png",
    Ethiopia: "https://flagcdn.com/w320/et.png",
    "Faeroe Islands": "https://flagcdn.com/w320/fo.png",
    "Falkland Islands Malvinas": "https://flagcdn.com/w320/fk.png",
    Fiji: "https://flagcdn.com/w320/fj.png",
    Finland: "https://flagcdn.com/w320/fi.png",
    France: "https://flagcdn.com/w320/fr.png",
    "French Guiana": "https://flagcdn.com/w320/gf.png",
    "French Polynesia": "https://flagcdn.com/w320/pf.png",
    Gabon: "https://flagcdn.com/w320/ga.png",
    Gambia: "https://flagcdn.com/w320/gm.png",
    Georgia: "https://flagcdn.com/w320/ge.png",
    Germany: "https://flagcdn.com/w320/de.png",
    Ghana: "https://flagcdn.com/w320/gh.png",
    Gibraltar: "https://flagcdn.com/w320/gi.png",
    Greece: "https://flagcdn.com/w320/gr.png",
    Greenland: "https://flagcdn.com/w320/gl.png",
    Grenada: "https://flagcdn.com/w320/gd.png",
    Guadeloupe: "https://flagcdn.com/w320/gp.png",
    Guatemala: "https://flagcdn.com/w320/gt.png",
    "Guinea Bissau": "https://flagcdn.com/w320/gw.png",
    Guinea: "https://flagcdn.com/w320/gn.png",
    Guyana: "https://flagcdn.com/w320/gy.png",
    Haiti: "https://flagcdn.com/w320/ht.png",
    "Holy See": "https://flagcdn.com/w320/va.png",
    Honduras: "https://flagcdn.com/w320/hn.png",
    Hungary: "https://flagcdn.com/w320/hu.png",
    Iceland: "https://flagcdn.com/w320/is.png",
    India: "https://flagcdn.com/w320/in.png",
    Indonesia: "https://flagcdn.com/w320/id.png",
    Iran: "https://flagcdn.com/w320/ir.png",
    Iraq: "https://flagcdn.com/w320/iq.png",
    Ireland: "https://flagcdn.com/w320/ie.png",
    "Isle Of Man": "https://flagcdn.com/w320/im.png",
    Israel: "https://flagcdn.com/w320/il.png",
    Italy: "https://flagcdn.com/w320/it.png",
    Jamaica: "https://flagcdn.com/w320/jm.png",
    Japan: "https://flagcdn.com/w320/jp.png",
    Jordan: "https://flagcdn.com/w320/jo.png",
    Kazakhstan: "https://flagcdn.com/w320/kz.png",
    Kenya: "https://flagcdn.com/w320/ke.png",
    Kiribati: "https://flagcdn.com/w320/ki.png",
    Kuwait: "https://flagcdn.com/w320/kw.png",
    Kyrgyzstan: "https://flagcdn.com/w320/kg.png",
    Laos: "https://flagcdn.com/w320/la.png",
    Latvia: "https://flagcdn.com/w320/lv.png",
    Lebanon: "https://flagcdn.com/w320/lb.png",
    Lesotho: "https://flagcdn.com/w320/ls.png",
    Liberia: "https://flagcdn.com/w320/lr.png",
    Libya: "https://flagcdn.com/w320/ly.png",
    Liechtenstein: "https://flagcdn.com/w320/li.png",
    Lithuania: "https://flagcdn.com/w320/lt.png",
    Luxembourg: "https://flagcdn.com/w320/lu.png",
    Macedonia: "https://flagcdn.com/w320/mk.png",
    Madagascar: "https://flagcdn.com/w320/mg.png",
    Malawi: "https://flagcdn.com/w320/mw.png",
    Malaysia: "https://flagcdn.com/w320/my.png",
    Maldives: "https://flagcdn.com/w320/mv.png",
    Mali: "https://flagcdn.com/w320/ml.png",
    Malta: "https://flagcdn.com/w320/mt.png",
    "Marshall Islands": "https://flagcdn.com/w320/mh.png",
    Martinique: "https://flagcdn.com/w320/mq.png",
    Mauritania: "https://flagcdn.com/w320/mr.png",
    Mauritius: "https://flagcdn.com/w320/mu.png",
    Mayotte: "https://flagcdn.com/w320/yt.png",
    Mexico: "https://flagcdn.com/w320/mx.png",
    Micronesia: "https://flagcdn.com/w320/fm.png",
    Moldova: "https://flagcdn.com/w320/md.png",
    Monaco: "https://flagcdn.com/w320/mc.png",
    Mongolia: "https://flagcdn.com/w320/mn.png",
    Montenegro: "https://flagcdn.com/w320/me.png",
    Montserrat: "https://flagcdn.com/w320/ms.png",
    Morocco: "https://flagcdn.com/w320/ma.png",
    Mozambique: "https://flagcdn.com/w320/mz.png",
    Myanmar: "https://flagcdn.com/w320/mm.png",
    Namibia: "https://flagcdn.com/w320/na.png",
    Nauru: "https://flagcdn.com/w320/nr.png",
    Nepal: "https://flagcdn.com/w320/np.png",
    Netherlands: "https://flagcdn.com/w320/nl.png",
    "New Caledonia": "https://flagcdn.com/w320/nc.png",
    "New Zealand": "https://flagcdn.com/w320/nz.png",
    Nicaragua: "https://flagcdn.com/w320/ni.png",
    Niger: "https://flagcdn.com/w320/ne.png",
    Nigeria: "https://flagcdn.com/w320/ng.png",
    Niue: "https://flagcdn.com/w320/nu.png",
    Norway: "https://flagcdn.com/w320/no.png",
    Oman: "https://flagcdn.com/w320/om.png",
    Pakistan: "https://flagcdn.com/w320/pk.png",
    Palau: "https://flagcdn.com/w320/pw.png",
    Panama: "https://flagcdn.com/w320/pa.png",
    "Papua New Guinea": "https://flagcdn.com/w320/pg.png",
    Paraguay: "https://flagcdn.com/w320/py.png",
    Peru: "https://flagcdn.com/w320/pe.png",
    Philippines: "https://flagcdn.com/w320/ph.png",
    Poland: "https://flagcdn.com/w320/pl.png",
    Portugal: "https://flagcdn.com/w320/pt.png",
    Qatar: "https://flagcdn.com/w320/qa.png",
    Reunion: "https://flagcdn.com/w320/re.png",
    Romania: "https://flagcdn.com/w320/ro.png",
    Russia: "https://flagcdn.com/w320/ru.png",
    Rwanda: "https://flagcdn.com/w320/rw.png",
    "Saint Barthelemy": "https://flagcdn.com/w320/bl.png",
    "Saint Helena": "https://flagcdn.com/w320/sh.png",
    "Saint Kitts And Nevis": "https://flagcdn.com/w320/kn.png",
    "Saint Lucia": "https://flagcdn.com/w320/lc.png",
    "Saint Martin": "https://flagcdn.com/w320/mf.png",
    "Saint Pierre And Miquelon": "https://flagcdn.com/w320/pm.png",
    "Saint Vincent And The Grenadines": "https://flagcdn.com/w320/vc.png",
    Samoa: "https://flagcdn.com/w320/ws.png",
    "San Marino": "https://flagcdn.com/w320/sm.png",
    "Sao Tome And Principe": "https://flagcdn.com/w320/st.png",
    "Saudi Arabia": "https://flagcdn.com/w320/sa.png",
    Senegal: "https://flagcdn.com/w320/sn.png",
    Serbia: "https://flagcdn.com/w320/rs.png",
    Seychelles: "https://flagcdn.com/w320/sc.png",
    "Sierra Leone": "https://flagcdn.com/w320/sl.png",
    Singapore: "https://flagcdn.com/w320/sg.png",
    "Sint Maarten": "https://flagcdn.com/w320/sx.png",
    Slovakia: "https://flagcdn.com/w320/sk.png",
    Slovenia: "https://flagcdn.com/w320/si.png",
    "Solomon Islands": "https://flagcdn.com/w320/sb.png",
    Somalia: "https://flagcdn.com/w320/so.png",
    "South Africa": "https://flagcdn.com/w320/za.png",
    "South Korea": "https://flagcdn.com/w320/kr.png",
    "South Sudan": "https://flagcdn.com/w320/ss.png",
    Spain: "https://flagcdn.com/w320/es.png",
    "Sri Lanka": "https://flagcdn.com/w320/lk.png",
    "State Of Palestine": "https://flagcdn.com/w320/ps.png",
    Sudan: "https://flagcdn.com/w320/sd.png",
    Suriname: "https://flagcdn.com/w320/sr.png",
    Swaziland: "https://flagcdn.com/w320/sz.png",
    Sweden: "https://flagcdn.com/w320/se.png",
    Switzerland: "https://flagcdn.com/w320/ch.png",
    Syria: "https://flagcdn.com/w320/sy.png",
    Taiwan: "https://flagcdn.com/w320/tw.png",
    Tajikistan: "https://flagcdn.com/w320/tj.png",
    Tanzania: "https://flagcdn.com/w320/tz.png",
    Thailand: "https://flagcdn.com/w320/th.png",
    "Timor Leste": "https://flagcdn.com/w320/tl.png",
    Togo: "https://flagcdn.com/w320/tg.png",
    Tonga: "https://flagcdn.com/w320/to.png",
    "Trinidad And Tobago": "https://flagcdn.com/w320/tt.png",
    Tunisia: "https://flagcdn.com/w320/tn.png",
    Turkey: "https://flagcdn.com/w320/tr.png",
    "Turks And Caicos Islands": "https://flagcdn.com/w320/tc.png",
    Uganda: "https://flagcdn.com/w320/ug.png",
    UK: "https://flagcdn.com/w320/gb.png",
    Ukraine: "https://flagcdn.com/w320/ua.png",
    "United Arab Emirates": "https://flagcdn.com/w320/ae.png",
    Uruguay: "https://flagcdn.com/w320/uy.png",
    USA: "https://flagcdn.com/w320/us.png",
    Uzbekistan: "https://flagcdn.com/w320/uz.png",
    Vanuatu: "https://flagcdn.com/w320/vu.png",
    Venezuela: "https://flagcdn.com/w320/ve.png",
    "Viet Nam": "https://flagcdn.com/w320/vn.png",
    "Wallis And Futuna Islands": "https://flagcdn.com/w320/wf.png",
    "Western Sahara": "https://flagcdn.com/w320/eh.png",
    Yemen: "https://flagcdn.com/w320/ye.png",
    Zambia: "https://flagcdn.com/w320/zm.png",
    Zimbabwe: "https://flagcdn.com/w320/zw.png",
  };
  